on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v7 # This action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes 
